import SideLeft from './SideLeft'
import SideRight from './SideRight'
import AuthProvider from '@/app/(auth)/provider'
import './globals.css'

export const metadata = {
  title: 'Threads Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-row'>
        <AuthProvider>
          <SideLeft />
          <main className='w-[65%]'>
            {children}
          </main>
          <SideRight />
        </AuthProvider>
      </body>
    </html>
  )
}
