import SideLeft from './SideLeft'
import SideRight from './SideRight'
import './globals.css'

export const metadata = {
  title: 'Threads Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-row'>
        <SideLeft />
        <main className='bg-red-600 w-[65%]'>
          {children}
        </main>
        <SideRight />
      </body>
    </html>
  )
}
